<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LeaveRequest extends Model
{
    use HasFactory;

    protected $table = 'leave_requests';

    // Mass assignable fields
    protected $fillable = [
        'year',
        'office',
        'person_id',
        'person_name',
        'department_name',
        'division_name',
        'employee_id',
        'leave_type',
        'on_behalf_request',
        'division_id',
        'department_id',
        'al_leave',
        'cl_leave',
        'sl_leave',
        'pat_leave',
        'mat_leave',
        'purpose_leave',
        'contact_address',
        'remarks',
        'total_leave',
        'office_text',
        'division_text',
        'employee_text',
        'balance_al',
        'balance_cl',
        'balance_sl',
        'balance_pat',
        'balance_mat',
        'balance_total',
        'al_start_date',
        'al_start_time',
        'al_end_date',
        'al_end_time',
        'cl_start_date',
        'cl_start_time',
        'cl_end_date',
        'cl_end_time',
        'sl_start_date',
        'sl_start_time',
        'sl_end_date',
        'sl_end_time',
        'mat_start_date',
        'mat_start_time',
        'mat_end_date',
        'mat_end_time',
        'pat_start_date',
        'pat_start_time',
        'pat_end_date',
        'pat_end_time',
        'reliver_employee',
        'leave_year',
        'p_cl',
        'p_sl',
        'others_emp_leave',
        'others_start_date',
        'others_end_date',
        'others_start_time',
        'others_end_time',
        'compensatory_leave',
        'compensatory_start_date',
        'compensatory_end_date',
        'compensatory_start_time',
        'compensatory_end_time',
        'notes',
        'lwp_leave',
        'lwp_start_date',
        'lwp_end_date',
        'lwp_start_time',
        'lwp_end_time',
        'status',
        'request_by',
        'request_date',
        'pass_by',
        'pass_note',
        'pass_date',
        'approved_by',
        'approved_by_name',
        'approved_by_designation',
        'approved_note',
        'approved_date',
        'entry_from',
        'inline_supervisor_id',
        'inline_supervisor_name',
        'inline_supervisor_designation',
        'request_for_approved',
        'request_for',
        'other_person',
        'other_person_text',
        'is_other_leave',
        'is_cancel',
        'hr_app_by',
        'hr_date',
        'hr_remarks',
        'hr_status',
    ];
}
